#!/usr/bin/env node
/* ============================================================
   The 40Yr Virgil — data migration builder (Phase 4 tooling)
   ------------------------------------------------------------
   Transforms the exported club data (a JSON dump of the XLSX —
   see dump-xlsx.mjs) into:
     1. migrate/import.sql   — one paste-into-the-D1-console file,
                                 the same workflow already used for
                                 schema.sql.
     2. A validation report printed to stdout (PASS/REVIEW/ERROR).

   This does NOT touch the live Worker/D1 — it only reads the export
   and writes a local SQL file + report. It is proven against a
   throwaway local SQLite copy of schema.sql before being trusted.

   Usage:
     node migrate/build-import.mjs <clubdata.json> [--current-from=<seq>] [--totals=<totals.json>]

   --current-from=<seq>  Owner-specified boundary: matches with
                          seq >= this number go in the CURRENT season;
                          everything before goes in a PREVIOUS season.
                          Can also be given as `currentSeasonStartSeq`
                          inside --totals instead. Omit both and every
                          match stays in one season (flagged REVIEW).
   --totals=<file>       The owner's private totals-reconciliation
                          file (never committed — see README and
                          totals.example.json for the shape). When
                          given, its overall/season figures become the
                          actual verified baselines written to the
                          import (not just a comparison).
   ============================================================ */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dir = dirname(fileURLToPath(import.meta.url));
const args = process.argv.slice(2);
const inputPath = args.find((a) => !a.startsWith("--"));
const currentFromArg = args.find((a) => a.startsWith("--current-from="));
const totalsArg = args.find((a) => a.startsWith("--totals="));
const CURRENT_FROM_SEQ = currentFromArg ? parseInt(currentFromArg.split("=")[1], 10) : null;
const totalsPath = totalsArg ? totalsArg.split("=")[1] : null;

if (!inputPath) {
  console.error("Usage: node build-import.mjs <clubdata.json> [--current-from=<seq>] [--totals=<file>]");
  process.exit(1);
}

const data = JSON.parse(readFileSync(inputPath, "utf8"));
const totals = totalsPath ? JSON.parse(readFileSync(totalsPath, "utf8")) : null;
const SEASON_BOUNDARY = CURRENT_FROM_SEQ != null ? CURRENT_FROM_SEQ : (totals && totals.currentSeasonStartSeq != null ? Number(totals.currentSeasonStartSeq) : null);

function cfgMap(rows) { const m = {}; (rows || []).forEach((r) => { m[r.key] = r.value; }); return m; }
function parseJSON(v, fallback) { try { return v ? JSON.parse(v) : fallback; } catch (e) { return fallback; } }
function n(v, d) { const x = Number(v); return isFinite(x) ? x : (d === undefined ? null : d); }
function pid(s) { return String(s == null ? "" : s).toLowerCase().replace(/[^a-z0-9_-]/g, "").slice(0, 24); }
function sqlStr(v) {
  if (v === null || v === undefined || v === "") return "NULL";
  return "'" + String(v).replace(/'/g, "''") + "'";
}
function sqlNum(v) { return v === null || v === undefined || v === "" ? "NULL" : Number(v); }
function sqlBool(v) { return v ? 1 : 0; }

const cfg = cfgMap(data.config);
const squad = parseJSON(cfg.squad, []);
const seasonsCfg = parseJSON(cfg.seasons, []);
const currentSeasonId = cfg.current_season || "fc26";
const baselineSeq = n(cfg.career_baseline_seq, 0);

const report = { pass: [], review: [], error: [] };
function PASS(msg) { report.pass.push(msg); }
function REVIEW(msg) { report.review.push(msg); }
function ERROR(msg) { report.error.push(msg); }

/* ---------- seasons ---------- */
const PREV_SEASON_ID = currentSeasonId + "_prev";
const sql = [];
sql.push("-- ============================================================");
sql.push("-- The 40Yr Virgil — data import (generated by build-import.mjs)");
sql.push("-- Paste into: Cloudflare dashboard → D1 → virgil → Console → Run.");
sql.push("-- Additive: safe to run once against a schema-only database.");
sql.push("-- ============================================================");
sql.push("");

const prevLabel = (totals && totals.previousSeasonLabel) || "Previous season";
const currentLabelOverride = totals && totals.currentSeasonLabel;

if (SEASON_BOUNDARY != null) {
  sql.push(`INSERT OR IGNORE INTO seasons (id,label,game,started_iso,ended_iso,archived,sort) VALUES ('${PREV_SEASON_ID}',${sqlStr(prevLabel)},'EA Sports FC 26','','',1,10);`);
  PASS(`Season split applied at seq ${SEASON_BOUNDARY}: matches < ${SEASON_BOUNDARY} → '${PREV_SEASON_ID}' (${prevLabel}), >= ${SEASON_BOUNDARY} → '${currentSeasonId}'${currentLabelOverride ? " (" + currentLabelOverride + ")" : ""}.`);
} else {
  REVIEW(`No season boundary given: all ${data.matches.length} matches will import into a single season ('${currentSeasonId}'). Provide the exact match number where the current season starts to split Season 2 (previous) from Season 3 (current) — see the plan's season-correction step.`);
}
(seasonsCfg.length ? seasonsCfg : [{ id: currentSeasonId, label: "Season · FC26", game: "EA Sports FC 26", startedISO: "", endedISO: "", archived: false }]).forEach((s) => {
  var label = (s.id === currentSeasonId && currentLabelOverride) ? currentLabelOverride : s.label;
  sql.push(`INSERT OR IGNORE INTO seasons (id,label,game,started_iso,ended_iso,archived,sort) VALUES (${sqlStr(s.id)},${sqlStr(label)},${sqlStr(s.game)},${sqlStr(s.startedISO)},${sqlStr(s.endedISO)},${sqlBool(s.archived)},20);`);
  if (s.id === currentSeasonId && currentLabelOverride) {
    sql.push(`UPDATE seasons SET label=${sqlStr(currentLabelOverride)} WHERE id=${sqlStr(s.id)};`);
  }
});
sql.push(`INSERT INTO site_settings (key,value) VALUES ('current_season',${sqlStr(currentSeasonId)}) ON CONFLICT(key) DO UPDATE SET value=excluded.value;`);
sql.push("");

/* ---------- players (from squad config) ---------- */
const playerIds = new Set();
squad.forEach((p) => {
  const id = pid(p.id);
  if (!id) return;
  playerIds.add(id);
  const positions = Array.isArray(p.positions) && p.positions.length ? p.positions : (p.position ? [p.position] : []);
  sql.push(`INSERT OR IGNORE INTO players (id,number,name,slug,controlled_by,is_human,perma_bench,retired_ai,linked_to,positions_json,flavour,active) VALUES (` +
    `${sqlStr(id)},${sqlNum(p.number)},${sqlStr(p.name)},${sqlStr(id)},${sqlStr(p.controlledBy || "bot")},${sqlBool(p.controlledBy === "human")},` +
    `${sqlBool(p.permaBench)},${sqlBool(p.retiredAI)},${p.linkedTo ? sqlStr(pid(p.linkedTo)) : "NULL"},${sqlStr(JSON.stringify(positions))},${sqlStr(p.flavour)},${sqlBool(!p.disabled)});`);
});
PASS(`${squad.length} squad players imported (identity only — card images need a separate R2 upload per player in Housekeeping).`);
const amy = squad.find((p) => pid(p.id) === "amy");
const donovan = squad.find((p) => pid(p.id) === "donovan");
if (amy && donovan) PASS("Amy and Donovan both present as separate player records (never merged).");
else if (amy && !donovan) REVIEW("Amy present but no separate Donovan record found in this export — confirm this is expected.");

/* Any player id referenced by scorers/stats but missing from the squad
   is dropped entirely — no guest placeholders, per the owner's explicit
   call (e.g. 'sway', removed from the squad earlier). The scoreline
   itself (our_score/their_score) is untouched — only the individual
   scorer/stat-line attribution for that id is left out, tracked here
   for full transparency in the report. */
const droppedPlayerIds = new Set();

/* ---------- career baselines ----------
   Start from the sheet's own `career` rows (as-of the old baseline seq),
   then let the owner's totals file OVERRIDE apps/goals/assists/avg_rating
   for any player it names — those are verified-as-of-today figures, so
   they're stamped with as_of_seq = the last match in this export. Any
   passing/tackling figures already on the sheet are preserved unless the
   totals file also corrects them. Amy gets a fresh row here even though
   she has no legacy `career` sheet entry (she's not in the EA-era data). */
const maxMatchSeq = (data.matches || []).reduce((mx, m) => Math.max(mx, n(m.seq, 0)), 0);
const careerRows = new Map();
(data.career || []).forEach((c) => {
  const id = pid(c.playerId);
  careerRows.set(id, {
    as_of_seq: baselineSeq, apps: n(c.games, 0), goals: n(c.goals, 0), assists: n(c.assists, 0), avg_rating: null,
    passes: n(c.passesMade, 0), tackles: n(c.tackles, 0), clean_sheets: n(c.cleanSheets, 0), win_pct: n(c.winPct),
    source: "EA archive import", note: null
  });
});
if (totals && Array.isArray(totals.players)) {
  totals.players.forEach((t) => {
    const id = pid(t.player_id);
    const prior = careerRows.get(id) || { passes: 0, tackles: 0, clean_sheets: 0, win_pct: null };
    careerRows.set(id, {
      as_of_seq: maxMatchSeq,
      apps: n(t.overall_apps, prior.apps || 0), goals: n(t.overall_goals, prior.goals || 0), assists: n(t.overall_assists, prior.assists || 0),
      avg_rating: t.overall_avg_rating != null ? n(t.overall_avg_rating) : (prior.avg_rating || null),
      passes: prior.passes || 0, tackles: prior.tackles || 0, clean_sheets: prior.clean_sheets || 0, win_pct: prior.win_pct,
      source: "Owner-verified totals", note: t.note || null
    });
  });
  PASS(`${totals.players.length} player(s) got owner-verified overall totals (apps/goals/assists), stamped as-of match ${maxMatchSeq} — the archive's own recorded contributions only add on top from match ${maxMatchSeq + 1} onward, so nothing double-counts.`);
}
careerRows.forEach((c, id) => {
  sql.push(`INSERT OR REPLACE INTO player_career_baselines (player_id,as_of_seq,apps,goals,assists,avg_rating,passes,tackles,clean_sheets,win_pct,source,note,updated_iso) VALUES (` +
    `${sqlStr(id)},${sqlNum(c.as_of_seq)},${sqlNum(c.apps)},${sqlNum(c.goals)},${sqlNum(c.assists)},${sqlNum(c.avg_rating)},${sqlNum(c.passes)},${sqlNum(c.tackles)},${sqlNum(c.clean_sheets)},${sqlNum(c.win_pct)},${sqlStr(c.source)},${sqlStr(c.note)},'${new Date().toISOString()}');`);
});
PASS(`${careerRows.size} verified career baselines imported in total.`);
sql.push("");

/* ---------- season baselines (from the owner's totals, if given) ---------- */
if (totals && Array.isArray(totals.players)) {
  totals.players.forEach((t) => {
    const id = pid(t.player_id);
    if (t.season_apps == null && t.season_goals == null && t.season_assists == null) return;
    sql.push(`INSERT OR REPLACE INTO player_season_baselines (player_id,season_id,apps,goals,assists,avg_rating,note) VALUES (` +
      `${sqlStr(id)},${sqlStr(currentSeasonId)},${sqlNum(t.season_apps, 0)},${sqlNum(t.season_goals, 0)},${sqlNum(t.season_assists, 0)},${sqlNum(t.season_avg_rating)},${sqlStr(t.note)});`);
  });
  PASS(`Current-season (${currentSeasonId}) verified baselines imported for ${totals.players.length} player(s).`);
}
sql.push("");

/* ---------- club record baseline ---------- */
(data.club_record || []).forEach((r) => {
  sql.push(`INSERT OR REPLACE INTO club_record_baselines (key,value) VALUES (${sqlStr(r.key)},${sqlStr(String(r.value))});`);
});
sql.push("");

/* ---------- matches + scorers ---------- */
let matchCount = 0;
(data.matches || []).forEach((m) => {
  const seq = n(m.seq); if (seq == null) return;
  matchCount++;
  const seasonId = SEASON_BOUNDARY != null ? (seq < SEASON_BOUNDARY ? PREV_SEASON_ID : currentSeasonId) : currentSeasonId;
  sql.push(`INSERT OR REPLACE INTO matches (id,season_id,stage,date_iso,opponent,our_score,their_score,result,note,comp_name,venue,motm_player_id,captain_player_id,formation,updated_by,updated_iso) VALUES (` +
    `${seq},${sqlStr(seasonId)},${sqlStr(m.stage || "league")},${sqlStr(m.dateISO)},${sqlStr(m.opponent)},${sqlNum(m.ourScore, 0)},${sqlNum(m.theirScore, 0)},${sqlStr(m.result)},` +
    `${sqlStr(m.note)},${sqlStr(m.compName)},${sqlStr(m.venue)},NULL,NULL,NULL,${sqlStr(m.updatedBy)},${sqlStr(m.updatedISO)});`);
  const scorers = parseJSON(m.scorersJson, []);
  scorers.forEach((s, i) => {
    const spid = pid(s.id);
    if (!playerIds.has(spid)) { droppedPlayerIds.add(spid); return; }
    sql.push(`INSERT OR REPLACE INTO match_scorers (match_id,player_id,goals,ord) VALUES (${seq},${sqlStr(spid)},${sqlNum(s.goals, 1)},${i});`);
  });
});
PASS(`${matchCount} matches imported, preserving seq order.`);
sql.push("");

/* ---------- match_player_stats ---------- */
let statCount = 0, statDropCount = 0;
(data.match_stats || []).forEach((s) => {
  const seq = n(s.seq); const spid = pid(s.playerId);
  if (seq == null || !spid) return;
  if (!playerIds.has(spid)) { droppedPlayerIds.add(spid); statDropCount++; return; }
  statCount++;
  sql.push(`INSERT OR REPLACE INTO match_player_stats (match_id,player_id,goals,assists,rating,shots,tackles,passes_made,pass_attempts,red_cards,saves,conceded) VALUES (` +
    `${seq},${sqlStr(spid)},${sqlNum(s.goals, 0)},${sqlNum(s.assists, 0)},${sqlNum(s.rating)},${sqlNum(s.shots, 0)},${sqlNum(s.tackles, 0)},${sqlNum(s.passesMade, 0)},${sqlNum(s.passAttempts, 0)},${sqlNum(s.redCards, 0)},${sqlNum(s.saves, 0)},${sqlNum(s.conceded, 0)});`);
});
PASS(`${statCount} per-player match stat lines imported.`);
if (droppedPlayerIds.size) {
  REVIEW(`Dropped entirely (not imported, no placeholder created) — player id(s) with no squad record: ${[...droppedPlayerIds].join(", ")}. Scorer/stat-line attributions for these ids were left out; each match's own scoreline (our_score/their_score) is untouched.${statDropCount ? ` ${statDropCount} stat line(s) dropped.` : ""}`);
}
sql.push("");

/* ---------- cross-check the owner's Season 3 totals against the archive's
   own stat lines for matches >= the boundary. If they match exactly, the
   detailed archive for the current season is complete and self-consistent
   with what the owner independently verified — the strongest possible
   confirmation this import is correct. ---------- */
if (totals && Array.isArray(totals.players) && SEASON_BOUNDARY != null) {
  const seasonAgg = {};
  (data.match_stats || []).forEach((s) => {
    const seq = n(s.seq); if (seq == null || seq < SEASON_BOUNDARY) return;
    const spid = pid(s.playerId);
    const agg = seasonAgg[spid] || (seasonAgg[spid] = { apps: 0, goals: 0, assists: 0 });
    agg.apps++; agg.goals += n(s.goals, 0); agg.assists += n(s.assists, 0);
  });
  totals.players.forEach((t) => {
    const id = pid(t.player_id);
    const agg = seasonAgg[id] || { apps: 0, goals: 0, assists: 0 };
    const match = agg.apps === n(t.season_apps) && agg.goals === n(t.season_goals) && agg.assists === n(t.season_assists);
    if (match) PASS(`${id}: archive-derived Season ${currentSeasonId} stats (apps ${agg.apps}, goals ${agg.goals}, assists ${agg.assists}) exactly match the owner's verified totals.`);
    else REVIEW(`${id}: archive-derived Season ${currentSeasonId} stats show apps ${agg.apps}/goals ${agg.goals}/assists ${agg.assists} vs the owner's verified apps ${t.season_apps}/goals ${t.season_goals}/assists ${t.season_assists} — the season baseline above uses the owner's verified figures regardless, so the site will show the right numbers either way; this is just flagging the archive has a gap somewhere for a human to look at if they want to.`);
  });
}
sql.push("");

/* ---------- accounts → users (hashes preserved as-is; legacy scheme) ---------- */
(data.accounts || []).forEach((a) => {
  sql.push(`INSERT OR IGNORE INTO users (username,display,level,banned,pw_hash,pw_salt,pw_algo,created_iso,last_iso) VALUES (` +
    `${sqlStr(String(a.userKey).toLowerCase())},${sqlStr(a.display)},${sqlNum(a.level, 1)},${sqlBool(a.banned)},${sqlStr(a.pwHash)},${sqlStr(a.pwSalt)},'sha256',${sqlStr(a.createdISO)},${sqlStr(a.lastISO)});`);
});
PASS(`${(data.accounts || []).length} accounts imported with their existing password hash untouched (pw_algo='sha256') — each one transparently upgrades to PBKDF2 the next time that person logs in. No passwords reset.`);
sql.push("");

/* ---------- chat (best-effort continuity; user_id resolved by username) ---------- */
sql.push("-- chat/forum import resolves user_id via a subselect on username, so it can run after the users insert above.");
(data.chat || []).forEach((c) => {
  if (!c.text) return;
  sql.push(`INSERT INTO chat_messages (user_id,display,level,body,created_iso,deleted_iso) SELECT id,${sqlStr(c.display)},${sqlNum(c.level, 1)},${sqlStr(c.text)},${sqlStr(c.ts_iso)},${c.deleted ? sqlStr(c.ts_iso) : "NULL"} FROM users WHERE username=${sqlStr(String(c.userKey).toLowerCase())};`);
});
sql.push("");

/* ---------- forum threads + posts (category resolved by key, user_id by username) ---------- */
(data.forum_threads || []).forEach((t) => {
  if (!t.title || !t.body) return;
  sql.push(
    `INSERT INTO forum_threads (category_id,user_id,title,body,created_iso,last_iso,replies,pinned) ` +
    `SELECT (SELECT id FROM forum_categories WHERE key=${sqlStr(t.category)}), u.id, ${sqlStr(t.title)}, ${sqlStr(t.body)}, ${sqlStr(t.ts_iso)}, ${sqlStr(t.lastISO || t.ts_iso)}, ${sqlNum(t.replies, 0)}, 0 ` +
    `FROM users u WHERE u.username=${sqlStr(String(t.userKey).toLowerCase())} ` +
    `AND NOT EXISTS (SELECT 1 FROM forum_threads ft WHERE ft.title=${sqlStr(t.title)} AND ft.created_iso=${sqlStr(t.ts_iso)});`
  );
});
(data.forum_posts || []).forEach((p) => {
  if (!p.body || !p.threadId) return;
  sql.push(
    `INSERT INTO forum_posts (thread_id,user_id,body,created_iso,deleted_iso) ` +
    `SELECT ft.id, u.id, ${sqlStr(p.body)}, ${sqlStr(p.ts_iso)}, ${p.deleted ? sqlStr(p.ts_iso) : "NULL"} ` +
    `FROM forum_threads ft, users u WHERE ft.title=${sqlStr(p.threadTitle || "")} AND u.username=${sqlStr(String(p.userKey).toLowerCase())} ` +
    `AND NOT EXISTS (SELECT 1 FROM forum_posts fp WHERE fp.body=${sqlStr(p.body)} AND fp.created_iso=${sqlStr(p.ts_iso)});`
  );
});
if ((data.forum_threads || []).length) PASS(`${data.forum_threads.length} forum thread(s) imported (with any posts) — resolved by category key + username, idempotent on re-run.`);
sql.push("");

writeFileSync(join(__dir, "import.sql"), sql.join("\n") + "\n");

/* ---------- cross-check against club_record baseline (if present) ---------- */
const recBy = {}; (data.club_record || []).forEach((r) => { recBy[r.key] = r.value; });
if (recBy.played != null && matchCount) {
  const gap = Number(recBy.played) - matchCount;
  if (gap > 0) PASS(`Club record says ${recBy.played} played overall vs ${matchCount} detailed matches in this export — the ${gap}-match gap is the pre-recording/EA-era baseline period (expected, not an error).`);
  else if (gap < 0) ERROR(`Detailed match count (${matchCount}) exceeds the club_record baseline (${recBy.played}) — investigate before import.`);
}

if (!totals) {
  REVIEW("No owner totals-reconciliation file supplied yet — this import uses only the archive's own numbers. Re-run with --totals=<file> once you have verified overall + current-season figures.");
}

/* ---------- print report ---------- */
console.log("\n=== VALIDATION REPORT ===\n");
console.log("PASS:");
report.pass.forEach((m) => console.log("  ✓ " + m));
console.log("\nREVIEW:");
(report.review.length ? report.review : ["(none)"]).forEach((m) => console.log("  ⚠ " + m));
console.log("\nERROR:");
(report.error.length ? report.error : ["(none)"]).forEach((m) => console.log("  ✗ " + m));
console.log(`\nWrote ${sql.length} SQL statements to migrate/import.sql`);
console.log(report.error.length ? "\nRESULT: ERROR — resolve before importing." : "\nRESULT: ready to import (review items are informational, not blocking).");
process.exit(report.error.length ? 1 : 0);
