#!/usr/bin/env node
/* ============================================================
   The 40Yr Virgil — data migration builder (Phase 4 tooling)
   ------------------------------------------------------------
   Transforms the exported club data (a JSON dump of the XLSX —
   see dump-xlsx.mjs) into:
     1. migrate/import.sql   — one paste-into-the-D1-console file,
                                 the same workflow already used for
                                 schema.sql.
     2. A validation report printed to stdout (PASS/REVIEW/ERROR).

   This does NOT touch the live Worker/D1 — it only reads the export
   and writes a local SQL file + report. It is proven against a
   throwaway local SQLite copy of schema.sql before being trusted.

   Usage:
     node migrate/build-import.mjs <clubdata.json> [--current-from=<seq>] [--totals=<totals.json>]

   --current-from=<seq>  Owner-specified boundary: matches with
                          seq >= this number go in the CURRENT season;
                          everything before goes in a PREVIOUS season.
                          Omit it and every match stays in one season
                          (flagged REVIEW) until the owner gives the
                          exact number.
   --totals=<file>       The owner's private totals-reconciliation
                          file (never committed — see README). Used
                          only to compare against archive-derived
                          numbers in the validation report; never
                          required to build the import.
   ============================================================ */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dir = dirname(fileURLToPath(import.meta.url));
const args = process.argv.slice(2);
const inputPath = args.find((a) => !a.startsWith("--"));
const currentFromArg = args.find((a) => a.startsWith("--current-from="));
const totalsArg = args.find((a) => a.startsWith("--totals="));
const CURRENT_FROM_SEQ = currentFromArg ? parseInt(currentFromArg.split("=")[1], 10) : null;
const totalsPath = totalsArg ? totalsArg.split("=")[1] : null;

if (!inputPath) {
  console.error("Usage: node build-import.mjs <clubdata.json> [--current-from=<seq>] [--totals=<file>]");
  process.exit(1);
}

const data = JSON.parse(readFileSync(inputPath, "utf8"));
const totals = totalsPath ? JSON.parse(readFileSync(totalsPath, "utf8")) : null;

function cfgMap(rows) { const m = {}; (rows || []).forEach((r) => { m[r.key] = r.value; }); return m; }
function parseJSON(v, fallback) { try { return v ? JSON.parse(v) : fallback; } catch (e) { return fallback; } }
function n(v, d) { const x = Number(v); return isFinite(x) ? x : (d === undefined ? null : d); }
function pid(s) { return String(s == null ? "" : s).toLowerCase().replace(/[^a-z0-9_-]/g, "").slice(0, 24); }
function sqlStr(v) {
  if (v === null || v === undefined || v === "") return "NULL";
  return "'" + String(v).replace(/'/g, "''") + "'";
}
function sqlNum(v) { return v === null || v === undefined || v === "" ? "NULL" : Number(v); }
function sqlBool(v) { return v ? 1 : 0; }

const cfg = cfgMap(data.config);
const squad = parseJSON(cfg.squad, []);
const seasonsCfg = parseJSON(cfg.seasons, []);
const currentSeasonId = cfg.current_season || "fc26";
const baselineSeq = n(cfg.career_baseline_seq, 0);

const report = { pass: [], review: [], error: [] };
function PASS(msg) { report.pass.push(msg); }
function REVIEW(msg) { report.review.push(msg); }
function ERROR(msg) { report.error.push(msg); }

/* ---------- seasons ---------- */
const PREV_SEASON_ID = currentSeasonId + "_prev";
const sql = [];
sql.push("-- ============================================================");
sql.push("-- The 40Yr Virgil — data import (generated by build-import.mjs)");
sql.push("-- Paste into: Cloudflare dashboard → D1 → virgil → Console → Run.");
sql.push("-- Additive: safe to run once against a schema-only database.");
sql.push("-- ============================================================");
sql.push("");

if (CURRENT_FROM_SEQ != null) {
  sql.push(`INSERT OR IGNORE INTO seasons (id,label,game,started_iso,ended_iso,archived,sort) VALUES ('${PREV_SEASON_ID}','Previous season','EA Sports FC 26','','',1,10);`);
  PASS(`Season split applied at seq ${CURRENT_FROM_SEQ}: matches < ${CURRENT_FROM_SEQ} → '${PREV_SEASON_ID}', >= ${CURRENT_FROM_SEQ} → '${currentSeasonId}'.`);
} else {
  REVIEW(`No --current-from boundary given: all ${data.matches.length} matches will import into a single season ('${currentSeasonId}'). Provide the exact match number where the current season starts to split Season 2 (previous) from Season 3 (current) — see the plan's season-correction step.`);
}
(seasonsCfg.length ? seasonsCfg : [{ id: currentSeasonId, label: "Season · FC26", game: "EA Sports FC 26", startedISO: "", endedISO: "", archived: false }]).forEach((s) => {
  sql.push(`INSERT OR IGNORE INTO seasons (id,label,game,started_iso,ended_iso,archived,sort) VALUES (${sqlStr(s.id)},${sqlStr(s.label)},${sqlStr(s.game)},${sqlStr(s.startedISO)},${sqlStr(s.endedISO)},${sqlBool(s.archived)},20);`);
});
sql.push(`INSERT INTO site_settings (key,value) VALUES ('current_season',${sqlStr(currentSeasonId)}) ON CONFLICT(key) DO UPDATE SET value=excluded.value;`);
sql.push("");

/* ---------- players (from squad config) ---------- */
const playerIds = new Set();
squad.forEach((p) => {
  const id = pid(p.id);
  if (!id) return;
  playerIds.add(id);
  const positions = Array.isArray(p.positions) && p.positions.length ? p.positions : (p.position ? [p.position] : []);
  sql.push(`INSERT OR IGNORE INTO players (id,number,name,slug,controlled_by,is_human,perma_bench,retired_ai,linked_to,positions_json,flavour,active) VALUES (` +
    `${sqlStr(id)},${sqlNum(p.number)},${sqlStr(p.name)},${sqlStr(id)},${sqlStr(p.controlledBy || "bot")},${sqlBool(p.controlledBy === "human")},` +
    `${sqlBool(p.permaBench)},${sqlBool(p.retiredAI)},${p.linkedTo ? sqlStr(pid(p.linkedTo)) : "NULL"},${sqlStr(JSON.stringify(positions))},${sqlStr(p.flavour)},${sqlBool(!p.disabled)});`);
});
PASS(`${squad.length} squad players imported (identity only — card images need a separate R2 upload per player in Housekeeping).`);
const amy = squad.find((p) => pid(p.id) === "amy");
const donovan = squad.find((p) => pid(p.id) === "donovan");
if (amy && donovan) PASS("Amy and Donovan both present as separate player records (never merged).");
else if (amy && !donovan) REVIEW("Amy present but no separate Donovan record found in this export — confirm this is expected.");

/* Pre-scan every player id referenced by scorers/stats and create a
   "Guest" placeholder row for any that aren't in the squad — BEFORE any
   match/stat rows are emitted, so the FK on player_id is always satisfied
   regardless of statement order in the final SQL file. */
const junkPlayerIds = new Set();
(data.matches || []).forEach((m) => { parseJSON(m.scorersJson, []).forEach((s) => { const spid = pid(s.id); if (spid && !playerIds.has(spid)) junkPlayerIds.add(spid); }); });
(data.match_stats || []).forEach((s) => { const spid = pid(s.playerId); if (spid && !playerIds.has(spid)) junkPlayerIds.add(spid); });
if (junkPlayerIds.size) {
  junkPlayerIds.forEach((jid) => {
    sql.push(`INSERT OR IGNORE INTO players (id,number,name,slug,controlled_by,is_human,active) VALUES (${sqlStr(jid)},0,${sqlStr("Guest · " + jid)},${sqlStr(jid)},'human',1,0);`);
  });
  REVIEW(`${junkPlayerIds.size} player id(s) appear in match stats/scorers but have no squad record: ${[...junkPlayerIds].join(", ")}. Auto-created as inactive "Guest" placeholders so their recorded stats aren't lost — confirm with the owner whether to keep as guests, rename, or merge before the real production import.`);
}
sql.push("");

/* ---------- career baselines ---------- */
(data.career || []).forEach((c) => {
  const id = pid(c.playerId);
  sql.push(`INSERT OR REPLACE INTO player_career_baselines (player_id,as_of_seq,apps,goals,assists,avg_rating,passes,tackles,clean_sheets,win_pct,source,note,updated_iso) VALUES (` +
    `${sqlStr(id)},${sqlNum(baselineSeq)},${sqlNum(c.games, 0)},${sqlNum(c.goals, 0)},${sqlNum(c.assists, 0)},NULL,${sqlNum(c.passesMade, 0)},${sqlNum(c.tackles, 0)},${sqlNum(c.cleanSheets, 0)},${sqlNum(c.winPct)},'EA archive import',NULL,'${new Date().toISOString()}');`);
});
PASS(`${(data.career || []).length} verified career baselines imported (as-of match seq ${baselineSeq}).`);
sql.push("");

/* ---------- club record baseline ---------- */
(data.club_record || []).forEach((r) => {
  sql.push(`INSERT OR REPLACE INTO club_record_baselines (key,value) VALUES (${sqlStr(r.key)},${sqlStr(String(r.value))});`);
});
sql.push("");

/* ---------- matches + scorers ---------- */
let matchCount = 0;
(data.matches || []).forEach((m) => {
  const seq = n(m.seq); if (seq == null) return;
  matchCount++;
  const seasonId = CURRENT_FROM_SEQ != null ? (seq < CURRENT_FROM_SEQ ? PREV_SEASON_ID : currentSeasonId) : currentSeasonId;
  sql.push(`INSERT OR REPLACE INTO matches (id,season_id,stage,date_iso,opponent,our_score,their_score,result,note,comp_name,venue,motm_player_id,captain_player_id,formation,updated_by,updated_iso) VALUES (` +
    `${seq},${sqlStr(seasonId)},${sqlStr(m.stage || "league")},${sqlStr(m.dateISO)},${sqlStr(m.opponent)},${sqlNum(m.ourScore, 0)},${sqlNum(m.theirScore, 0)},${sqlStr(m.result)},` +
    `${sqlStr(m.note)},${sqlStr(m.compName)},${sqlStr(m.venue)},NULL,NULL,NULL,${sqlStr(m.updatedBy)},${sqlStr(m.updatedISO)});`);
  const scorers = parseJSON(m.scorersJson, []);
  scorers.forEach((s, i) => {
    const spid = pid(s.id);
    sql.push(`INSERT OR REPLACE INTO match_scorers (match_id,player_id,goals,ord) VALUES (${seq},${sqlStr(spid)},${sqlNum(s.goals, 1)},${i});`);
  });
});
PASS(`${matchCount} matches imported, preserving seq order.`);
sql.push("");

/* ---------- match_player_stats ---------- */
let statCount = 0;
(data.match_stats || []).forEach((s) => {
  const seq = n(s.seq); const spid = pid(s.playerId);
  if (seq == null || !spid) return;
  statCount++;
  sql.push(`INSERT OR REPLACE INTO match_player_stats (match_id,player_id,goals,assists,rating,shots,tackles,passes_made,pass_attempts,red_cards,saves,conceded) VALUES (` +
    `${seq},${sqlStr(spid)},${sqlNum(s.goals, 0)},${sqlNum(s.assists, 0)},${sqlNum(s.rating)},${sqlNum(s.shots, 0)},${sqlNum(s.tackles, 0)},${sqlNum(s.passesMade, 0)},${sqlNum(s.passAttempts, 0)},${sqlNum(s.redCards, 0)},${sqlNum(s.saves, 0)},${sqlNum(s.conceded, 0)});`);
});
PASS(`${statCount} per-player match stat lines imported.`);
sql.push("");

/* ---------- accounts → users (hashes preserved as-is; legacy scheme) ---------- */
(data.accounts || []).forEach((a) => {
  sql.push(`INSERT OR IGNORE INTO users (username,display,level,banned,pw_hash,pw_salt,pw_algo,created_iso,last_iso) VALUES (` +
    `${sqlStr(String(a.userKey).toLowerCase())},${sqlStr(a.display)},${sqlNum(a.level, 1)},${sqlBool(a.banned)},${sqlStr(a.pwHash)},${sqlStr(a.pwSalt)},'sha256',${sqlStr(a.createdISO)},${sqlStr(a.lastISO)});`);
});
PASS(`${(data.accounts || []).length} accounts imported with their existing password hash untouched (pw_algo='sha256') — each one transparently upgrades to PBKDF2 the next time that person logs in. No passwords reset.`);
sql.push("");

/* ---------- chat (best-effort continuity; user_id resolved by username) ---------- */
sql.push("-- chat/forum import resolves user_id via a subselect on username, so it can run after the users insert above.");
(data.chat || []).forEach((c) => {
  if (!c.text) return;
  sql.push(`INSERT INTO chat_messages (user_id,display,level,body,created_iso,deleted_iso) SELECT id,${sqlStr(c.display)},${sqlNum(c.level, 1)},${sqlStr(c.text)},${sqlStr(c.ts_iso)},${c.deleted ? sqlStr(c.ts_iso) : "NULL"} FROM users WHERE username=${sqlStr(String(c.userKey).toLowerCase())};`);
});
sql.push("");

writeFileSync(join(__dir, "import.sql"), sql.join("\n") + "\n");

/* ---------- cross-check against club_record baseline (if present) ---------- */
const recBy = {}; (data.club_record || []).forEach((r) => { recBy[r.key] = r.value; });
if (recBy.played != null && matchCount) {
  const gap = Number(recBy.played) - matchCount;
  if (gap > 0) PASS(`Club record says ${recBy.played} played overall vs ${matchCount} detailed matches in this export — the ${gap}-match gap is the pre-recording/EA-era baseline period (expected, not an error).`);
  else if (gap < 0) ERROR(`Detailed match count (${matchCount}) exceeds the club_record baseline (${recBy.played}) — investigate before import.`);
}

/* ---------- owner totals comparison (only if supplied) ---------- */
if (totals) {
  (totals.players || []).forEach((t) => {
    REVIEW(`Owner-supplied total for ${t.player_id}: apps=${t.overall_apps}, goals=${t.overall_goals} — compare against the baseline above once loaded; update via /api/admin/players/:id/baseline if different.`);
  });
} else {
  REVIEW("No owner totals-reconciliation file supplied yet — this import uses only the archive's own numbers. Re-run with --totals=<file> once you have verified overall + current-season figures, to cross-check before the real production import.");
}

/* ---------- print report ---------- */
console.log("\n=== VALIDATION REPORT ===\n");
console.log("PASS:");
report.pass.forEach((m) => console.log("  ✓ " + m));
console.log("\nREVIEW:");
(report.review.length ? report.review : ["(none)"]).forEach((m) => console.log("  ⚠ " + m));
console.log("\nERROR:");
(report.error.length ? report.error : ["(none)"]).forEach((m) => console.log("  ✗ " + m));
console.log(`\nWrote ${sql.length} SQL statements to migrate/import.sql`);
console.log(report.error.length ? "\nRESULT: ERROR — resolve before importing." : "\nRESULT: ready to import (review items are informational, not blocking).");
process.exit(report.error.length ? 1 : 0);
